spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: JourneyPlanner
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    hikari:
      max-lifetime: 170000
  thymeleaf:
    prefix: classpath:/META-INF/templates
    suffix: .html
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-in-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_IN} # 60000 : 1분
  refresh-token-expiration-in-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_IN}

springdoc:
  webjars:
    prefix:
  api-docs:
    path: /journey-planner/api-docs
    groups:
      enabled: true
  swagger-ui:
    urls:
      - url: /journey-planner/api-docs
        name: all
      - url: /journey-planner/api-docs/member
        name: Normal Member
      - url: /journey-planner/api-docs/websocket
        name: WebSocket
      - url: /journey-planner/api-docs/admin
        name: Admin Member
    path: /journey-planner/swagger
    disable-swagger-default-url: true
    config-url: /journey-planner/global/config
  default-produces-media-type: application/json

# Redis
redis:
  channel:
    name: topics
    stream:
      group-name: journey-planner-plans
