spring:
  config:
    import: optional:file:dev.env[.properties]
  application:
    name: JourneyPlanner
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: test
    url: jdbc:h2:mem:journey-planner;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-in-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_IN} # 60000 : 1분
  refresh-token-expiration-in-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_IN}