spring:
  application:
    name: JourneyPlanner
  datasource:
    driver-class-name: org.h2.Driver
    username:
    password:
    url:
  thymeleaf:
    prefix: classpath:/META-INF/templates
    suffix: .html