spring:
  application:
    name: JourneyPlanner
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: test
    url: jdbc:h2:mem:journey-planner;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  h2:
    console:
      enabled: true
      path: /h2-console