# 워크플로우 이름
name: Generate and Commit AsyncAPI Docs to Project

# 언제 실행할지 정의
on:
  push:
    branches:
      - develop

jobs:
  # 문서 생성 및 커밋 작업
  build-and-commit-docs:
    runs-on: ubuntu-latest # 실행 환경
    steps:
      # 1. 저장소 코드 가져오기
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. AsyncAPI 문서를 static 폴더에 생성
      - name: Generate AsyncAPI HTML documentation
        uses: asyncapi/cli@v3.0.1
        with:
          # 명령어를 직접 입력
          command: custom
          custom_command: >
            generate fromTemplate ./asyncapi.yaml @asyncapi/html-template@3.0.0
            --output ./src/main/resources/static/async-api-docs
            --use-new-generator

      # 3. 생성된 문서를 Git 저장소에 다시 커밋 및 푸시
      - name: Commit and push generated HTML files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # 커밋 메시지를 지정합니다.
          commit_message: "docs: Async API 문서 자동 생성"